import { Room, RoomEvent, Track, createLocalTracks } from 'livekit-client';
import { VideoProvider } from './VideoProvider';

export class LiveWebRTCProvider extends VideoProvider {
  constructor() { super(); this.state = { connected: false, microphone: true, camera: true, screenShare: false, localStream: null, remoteStream: null, participantCount: 0 }; this.listeners = new Set(); this.room = null; this.localTracks = []; }
  emit() { this.listeners.forEach((listener) => listener(this.state)); }
  subscribe(listener) { this.listeners.add(listener); return () => this.listeners.delete(listener); }
  rebuildStreams() { const local = this.localTracks.map((track) => track.mediaStreamTrack).filter(Boolean); const remote = []; this.room?.remoteParticipants.forEach((participant) => participant.trackPublications.forEach((publication) => publication.track?.mediaStreamTrack && remote.push(publication.track.mediaStreamTrack))); this.state.localStream = local.length ? new MediaStream(local) : null; this.state.remoteStream = remote.length ? new MediaStream(remote) : null; this.state.participantCount = (this.room?.remoteParticipants.size || 0) + 1; this.emit(); }
  async connect(roomId) { const identity = `guest-${crypto.randomUUID()}`; const response = await fetch(`/token?room=${encodeURIComponent(roomId)}&identity=${encodeURIComponent(identity)}`); if (!response.ok) throw new Error('Token LiveKit indisponible'); const { token, url } = await response.json(); if (!url) throw new Error('URL LiveKit absente'); this.room = new Room({ adaptiveStream: true, dynacast: true }); this.room.on(RoomEvent.TrackSubscribed, () => this.rebuildStreams()).on(RoomEvent.TrackUnsubscribed, () => this.rebuildStreams()).on(RoomEvent.ParticipantConnected, () => this.rebuildStreams()).on(RoomEvent.ParticipantDisconnected, () => this.rebuildStreams()); await this.room.connect(url, token); this.localTracks = await createLocalTracks({ audio: true, video: true }); for (const track of this.localTracks) await this.room.localParticipant.publishTrack(track); this.state.connected = true; this.rebuildStreams(); return this.state; }
  async disconnect() { this.localTracks.forEach((track) => track.stop()); await this.room?.disconnect(); this.room = null; this.localTracks = []; this.state = { ...this.state, connected: false, localStream: null, remoteStream: null, participantCount: 0 }; this.emit(); }
  async setMicrophoneEnabled(enabled) { await this.room?.localParticipant.setMicrophoneEnabled(enabled); this.state.microphone = enabled; this.emit(); return enabled; }
  async setCameraEnabled(enabled) { await this.room?.localParticipant.setCameraEnabled(enabled); this.state.camera = enabled; this.emit(); return enabled; }
  async setScreenShareEnabled(enabled) { await this.room?.localParticipant.setScreenShareEnabled(enabled); this.state.screenShare = enabled; this.emit(); return enabled; }
  async listDevices() { const devices = await navigator.mediaDevices.enumerateDevices(); return { microphones: devices.filter((device) => device.kind === 'audioinput').map((device) => ({ id: device.deviceId, label: device.label || 'Microphone' })), cameras: devices.filter((device) => device.kind === 'videoinput').map((device) => ({ id: device.deviceId, label: device.label || 'Camera' })), speakers: devices.filter((device) => device.kind === 'audiooutput').map((device) => ({ id: device.deviceId, label: device.label || 'Speaker' })) }; }
}
